@URL = http://localhost:5000

### Create one product
POST {{URL}}/products
Content-Type: application/json

{
  "name": "Tiritas de pescado",
  "price": 300.2,
  "description": "Tiritas de pescado en limon"
}

### Read all products
GET {{URL}}/products


### Read one product
GET {{URL}}/products/17

### Update one product
PUT {{URL}}/products/17
Content-Type: application/json

{
  "name": "tacos c",
  "price": 260.50,
  "description": "Tacos de cecina con guacamole"
}

### Delete one product
DELETE  {{URL}}/products/17
